#!/bin/bash

# Function to create a virtual environment
create_venv() {

    local env_name=${1:-".venv"}

    if [ -d "$env_name" ]; then
        echo "Virtual environment '$env_name' already exists. Aborting."
        return 1
    fi

    python3 -m venv "$env_name"
    source "./$env_name/bin/activate"
    pip install --upgrade pip
}

# Function to install dependencies from requirements.txt
install_deps() {
    local env_name=${1:-".venv"}

    if [ ! -d "$env_name" ]; then
        echo "Virtual environment '$env_name' not found. Use '$0 create [env_name]' to create one."
        return 1
    fi

    source "./$env_name/bin/activate"

    if [ -f "requirements.txt" ]; then
        pip install -r ./requirements.txt
    fi
}

# Check if packages.txt exists and is readable
if [[ -f packages.txt && -r packages.txt ]]; then
    sudo apt-get update
    xargs sudo apt-get --yes install < packages.txt
else
    echo "packages.txt does not exist or is not readable."
fi

# Check if requirements.txt exists and is readable
if [[ -f requirements.txt && -r requirements.txt ]]; then
    create_venv
    install_deps
else
    echo "requirements.txt does not exist or is not readable."
fi
