#!/bin/bash

# Check if packages.txt exists and is readable
if [[ -f packages.txt && -r packages.txt ]]; then
    sudo apt-get update
    xargs sudo apt-get --yes install < packages.txt
else
    echo "packages.txt does not exist or is not readable."
fi
