on:
 workflow_dispatch:
 push:
   branches:
     - main

jobs:
  build-generic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install build bundler
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          export VCS_REF=$(git rev-parse HEAD)
          npm install -g @devcontainers/cli

      - name: Build Generic
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          devcontainer build \
            --workspace-folder ./devcontainers/generic/ \
              --image-name artbashkirev/codespace:generic
        
      - name: Tag Generic
        run: |
          docker tag artbashkirev/codespace:generic artbashkirev/codespace:generic-${{ github.sha }}
          docker tag artbashkirev/codespace:generic artbashkirev/codespace:latest

      - name: Push to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push artbashkirev/codespace:generic-${{ github.sha }}
          docker push artbashkirev/codespace:generic
          docker push artbashkirev/codespace:latest

  build-ml:
    runs-on: ubuntu-latest
    needs: ["build-generic"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install build bundler
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          export VCS_REF=$(git rev-parse HEAD)
          npm install -g @devcontainers/cli

      - name: Build ML
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          devcontainer build \
            --workspace-folder ./devcontainers/ml/ \
              --image-name artbashkirev/codespace:ml

      - name: Tag Generic
        run: |
          docker tag artbashkirev/codespace:ml artbashkirev/codespace:ml-${{ github.sha }}

      - name: Push to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push artbashkirev/codespace:ml-${{ github.sha }}
          docker push artbashkirev/codespace:ml

  build-webdev:
    runs-on: ubuntu-latest
    needs: ["build-generic"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install build bundler
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          export VCS_REF=$(git rev-parse HEAD)
          npm install -g @devcontainers/cli

      - name: Build WebDev
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          devcontainer build \
            --workspace-folder ./devcontainers/webdev/ \
              --image-name artbashkirev/codespace:webdev
  
      - name: Tag Generic
        run: |
          docker tag artbashkirev/codespace:webdev artbashkirev/codespace:webdev-${{ github.sha }}

      - name: Push to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push artbashkirev/codespace:webdev-${{ github.sha }}
          docker push artbashkirev/codespace:webdev

  build-competition:
    runs-on: ubuntu-latest
    # needs: ["build-generic"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install build bundler
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          export VCS_REF=$(git rev-parse HEAD)
          npm install -g @devcontainers/cli

      - name: Build competition
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          devcontainer build \
            --workspace-folder ./devcontainers/competition/ \
              --image-name artbashkirev/codespace:competition
  
      - name: Tag Generic
        run: |
          docker tag artbashkirev/codespace:competition artbashkirev/codespace:competition-${{ github.sha }}

      - name: Push to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push artbashkirev/codespace:competition-${{ github.sha }}
          docker push artbashkirev/codespace:competition
