name: Build Competition

on:
 workflow_dispatch:
 push:
    branches:
      - main
    paths:
      - 'devcontainers/competition/*'
      - '.github/workflows/build-competition.yml'

jobs:
  build-competition:
   runs-on: ubuntu-latest
   continue-on-error: false
   strategy:
      fail-fast: true
   steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Install build bundler
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          export VCS_REF=$(git rev-parse HEAD)
          npm install -g @devcontainers/cli
  
      - name: Build competition
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          devcontainer build \
            --workspace-folder ./devcontainers/competition/ \
              --image-name ${{ secrets.DOCKERHUB_USERNAME }}/codespace:competition
  
      - name: Tag Competition
        run: |
          # docker tag ${{ secrets.DOCKERHUB_USERNAME }}/codespace:competition ${{ secrets.DOCKERHUB_USERNAME }}/codespace:competition-${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/codespace:competition ${{ secrets.DOCKERHUB_USERNAME }}/codespace:comp
  
      - name: Push to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          # docker push ${{ secrets.DOCKERHUB_USERNAME }}/codespace:competition-${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/codespace:competition
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/codespace:comp
