name: Build and Push Docker Images

on:
 workflow_dispatch:
 push:
    branches:
      - main
    paths-ignore:
      - "dist/**"
 schedule:
    - cron: "0 0 * * 0"

jobs:
 build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['generic', 'ml', 'webdev', 'competition']
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install build bundler
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          export VCS_REF=$(git rev-parse HEAD)
          npm install -g @devcontainers/cli

      - name: Build and Push
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          devcontainer build \
            --workspace-folder ./devcontainers/${{ matrix.image }}/ \
              --image-name ${{ secrets.DOCKERHUB_USERNAME }}/codespace:${{ matrix.image }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/codespace:${{ matrix.image }} artbashkirev/codespace:${{ matrix.image }}-latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/codespace:${{ matrix.image }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/codespace:${{ matrix.image }}-latest
