name: Build and Push Docker Images

on:
 workflow_dispatch:
 push:
    branches:
      - main
    paths-ignore:
      - "dist/**"
      - ".github/workflow/build-competition.yml"
      - "devcontainers/competition/*"
 schedule:
    - cron: "0 0 * * 0"

jobs:
 build-and-push:
    runs-on: ubuntu-latest
    needs: build-generic
    strategy:
      matrix:
        image: ['ml', 'webdev']
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install build bundler
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          export VCS_REF=$(git rev-parse HEAD)
          npm install -g @devcontainers/cli

      - name: Build and Push
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          devcontainer build \
            --workspace-folder ./devcontainers/${{ matrix.image }}/ \
              --image-name ${{ secrets.DOCKERHUB_USERNAME }}/codespace:${{ matrix.image }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/codespace:${{ matrix.image }} ${{ secrets.DOCKERHUB_USERNAME }}/codespace:${{ matrix.image }}-latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/codespace:${{ matrix.image }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/codespace:${{ matrix.image }}-latest
 build-generic:
     runs-on: ubuntu-latest
     strategy:
       fail-fast: true
     steps:
       - name: Checkout
         uses: actions/checkout@v4
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
       - name: Log into Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       - name: Install build bundler
         if: ${{ github.ref == 'refs/heads/main' }}
         run: |
           export VCS_REF=$(git rev-parse HEAD)
           npm install -g @devcontainers/cli
 
       - name: Build and Push
         if: ${{ github.ref == 'refs/heads/main' }}
         run: |
           devcontainer build \
             --workspace-folder ./devcontainers/generic/ \
               --image-name ${{ secrets.DOCKERHUB_USERNAME }}/codespace:generic
           docker tag ${{ secrets.DOCKERHUB_USERNAME }}/codespace:generic ${{ secrets.DOCKERHUB_USERNAME }}/codespace:latest
           docker push ${{ secrets.DOCKERHUB_USERNAME }}/codespace:generic
           docker push ${{ secrets.DOCKERHUB_USERNAME }}/codespace:latest
       
      
