on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install build bundler
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          export VCS_REF=$(git rev-parse HEAD)
          npm install -g @devcontainers/cli

      - name: Build Generic
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          devcontainer build --workspace-folder . --config devcontainer.json --image-name cs50/codespace:${{ github.sha }} --image-name cs50/codespace:latest

      - name: Push to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push cs50/codespace:${{ github.sha }}
          docker push cs50/codespace:latest
